# 详细参数说明：http://jekyllcn.com/docs/configuration/

# 目录结构
#source:      .
#destination: ./_site
#plugins:     ./_plugins
#layouts_dir:     ./_layouts
#data_dir: ./_data
#collections: null

# 阅读处理
#safe:         false
#encoding: 'utf-8'
#keep_files: [".git", ".svn"]
#markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# 内容过滤
#show_drafts: null
#limit_posts: 0
#用将来的日期发布文章
#future: true
#unpublished: false

# Site settings
title: Zero Blog
SEOTitle: 曾志伟的博客 | Zero Blog
header-img: img/home-bg.jpg
email: 308164213@qq.com
description: "茶能醉我何须，书能香我不须花。"
keyword: ""
url: "aver58.github.io"              # your host, for absolute URL

# 服务器选项
#detach:  false
#port:    4000
#host:    127.0.0.1
baseurl: "" # for example, '/blog' if your blog hosted on 'host/blog'

# SNS settings
RSS: false
weibo_username: 308164213
zhihu_username: ceng-zhi-wei-48
github_username: Aver58
#twitter_username:  huxpro
#facebook_username:  huxpro

# 转换
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 6
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
#  为相关文章生成索引
#lsi:         false

# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]
#plugins:
#  - jekyll-feed

# Disqus settings
#disqus_username: _your_disqus_short_name_

# Duoshuo settings
duoshuo_username: 曾志伟
# Share component is depend on Comment so we can NOT use share only.
#duoshuo_share: true                     # set to false if you want to use Comment without Sharing

livere_uid: MTAyMC8yODg4Mi81NDUy

# Analytics settings
# Baidu Analytics
ba_track_id: 207a182a0a79e8a76bfd02381045166f
# Google Analytics
#ga_track_id: 'UA-49627206-1'            # Format: UA-xxxxxx-xx
#ga_domain: huangxuan.me


# Sidebar settings
sidebar: true                # whether or not using Sidebar.
sidebar-about-description: "无目的地读书是散步不是学习。"
sidebar-avatar: /img/avatar-zhiwei.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Friends
friends: [
    {
        title: "Hux Blog",
        href: "http://huangxuan.me"
    },{
        title: "雨松MOMO的Blog",
        href: "http://www.xuanyusong.com/"
    },{
        title: "云风的Blog",
        href: "http://blog.codingnow.com/"
    },{
        title: "Kanglai的Blog",
        href: "http://qiankanglai.me/"
    }
]
